# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-config.matzat.cloud"
    dynamodb_table = "terraform_locks"
    encrypt        = true
    key            = "globals/service/mailimport/terraform.tfstate"
    region         = "eu-central-1"
  }
}
