name: Dependency Submission

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-and-gradle

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
